diff --ignore-space-change --unified plugins/contrib/AutoVersioning/AutoVersioning_wx32_64.cbp plugins/contrib/AutoVersioning/AutoVersioning_wxMSW32-msys2.cbp > AutoVersioning.diff
diff --ignore-space-change --unified plugins/contrib/BrowseTracker/BrowseTracker_wx32_64.cbp plugins/contrib/BrowseTracker/BrowseTracker_wxMSW32-msys2.cbp > BrowseTracker.diff
diff --ignore-space-change --unified plugins/contrib/byogames/byogames_wx32_64.cbp plugins/contrib/byogames/byogames_wxMSW32-msys2.cbp > byogames.diff
diff --ignore-space-change --unified plugins/contrib/codesnippets/codesnippets_wx32_64.cbp plugins/contrib/codesnippets/codesnippets_wxMSW32-msys2.cbp > codesnippets.diff
diff --ignore-space-change --unified plugins/contrib/codestat/codestat_wx32_64.cbp plugins/contrib/codestat/codestat_wxMSW32-msys2.cbp > codestat.diff
diff --ignore-space-change --unified plugins/contrib/copystrings/copystrings_wx32_64.cbp plugins/contrib/copystrings/copystrings_wxMSW32-msys2.cbp > copystrings.diff
diff --ignore-space-change --unified plugins/contrib/CppCheck/CppCheck_wx32_64.cbp plugins/contrib/CppCheck/CppCheck_wxMSW32-msys2.cbp > CppCheck.diff
diff --ignore-space-change --unified plugins/contrib/Cscope/Cscope_wx32_64.cbp plugins/contrib/Cscope/Cscope_wxMSW32-msys2.cbp > Cscope.diff
diff --ignore-space-change --unified plugins/contrib/DoxyBlocks/DoxyBlocks_wx32_64.cbp plugins/contrib/DoxyBlocks/DoxyBlocks_wxMSW32-msys2.cbp > DoxyBlocks.diff
diff --ignore-space-change --unified plugins/contrib/dragscroll/DragScroll_wx32_64.cbp plugins/contrib/dragscroll/DragScroll_wxMSW32-msys2.cbp > DragScroll.diff
diff --ignore-space-change --unified plugins/contrib/EditorConfig/EditorConfig_wx32_64.cbp plugins/contrib/EditorConfig/EditorConfig_wxMSW32-msys2.cbp > EditorConfig.diff
diff --ignore-space-change --unified plugins/contrib/EditorTweaks/EditorTweaks_wx32_64.cbp plugins/contrib/EditorTweaks/EditorTweaks_wxMSW32-msys2.cbp > EditorTweaks.diff
diff --ignore-space-change --unified plugins/contrib/envvars/envvars_wx32_64.cbp plugins/contrib/envvars/envvars_wxMSW32-msys2.cbp > envvars.diff
diff --ignore-space-change --unified plugins/contrib/FileManager/FileManager_wx32_64.cbp plugins/contrib/FileManager/FileManager_wxMSW32-msys2.cbp > FileManager.diff
diff --ignore-space-change --unified plugins/contrib/headerfixup/headerfixup_wx32_64.cbp plugins/contrib/headerfixup/headerfixup_wxMSW32-msys2.cbp > headerfixup.diff
diff --ignore-space-change --unified plugins/contrib/help_plugin/help-plugin_wx32_64.cbp plugins/contrib/help_plugin/help-plugin_wxMSW32-msys2.cbp > help-plugin.diff
diff --ignore-space-change --unified plugins/contrib/HexEditor/HexEditor_wx32_64.cbp plugins/contrib/HexEditor/HexEditor_wxMSW32-msys2.cbp > HexEditor.diff
diff --ignore-space-change --unified plugins/contrib/IncrementalSearch/IncrementalSearch_wx32_64.cbp plugins/contrib/IncrementalSearch/IncrementalSearch_wxMSW32-msys2.cbp > IncrementalSearch.diff
diff --ignore-space-change --unified plugins/contrib/keybinder/keybinder_wx32_64.cbp plugins/contrib/keybinder/keybinder_wxMSW32-msys2.cbp > keybinder.diff
diff --ignore-space-change --unified plugins/contrib/lib_finder/lib_finder_wx32_64.cbp plugins/contrib/lib_finder/lib_finder_wxMSW32-msys2.cbp > lib_finder.diff
diff --ignore-space-change --unified plugins/contrib/MouseSap/MouseSap_wx32_64.cbp plugins/contrib/MouseSap/MouseSap_wxMSW32-msys2.cbp > MouseSap.diff
diff --ignore-space-change --unified plugins/contrib/NassiShneiderman/NassiShneiderman_wx32_64.cbp plugins/contrib/NassiShneiderman/NassiShneiderman_wxMSW32-msys2.cbp > NassiShneiderman.diff
diff --ignore-space-change --unified plugins/contrib/profiler/cbprofiler_wx32_64.cbp plugins/contrib/profiler/cbprofiler_wxMSW32-msys2.cbp > cbprofiler.diff
diff --ignore-space-change --unified plugins/contrib/ProjectOptionsManipulator/ProjectOptionsManipulator_wx32_64.cbp plugins/contrib/ProjectOptionsManipulator/ProjectOptionsManipulator_wxMSW32-msys2.cbp > ProjectOptionsManipulator.diff
diff --ignore-space-change --unified plugins/contrib/regex_testbed/RegExTestbed_wx32_64.cbp plugins/contrib/regex_testbed/RegExTestbed_wxMSW32-msys2.cbp > RegExTestbed.diff
diff --ignore-space-change --unified plugins/contrib/ReopenEditor/ReopenEditor_wx32_64.cbp plugins/contrib/ReopenEditor/ReopenEditor_wxMSW32-msys2.cbp > ReopenEditor.diff
diff --ignore-space-change --unified plugins/contrib/rndgen/rndgen_wx32_64.cbp plugins/contrib/rndgen/rndgen_wxMSW32-msys2.cbp > rndgen.diff
diff --ignore-space-change --unified plugins/contrib/SmartIndent/SmartIndent_wx32_64.cbp plugins/contrib/SmartIndent/SmartIndent_wxMSW32-msys2.cbp > SmartIndent.diff
diff --ignore-space-change --unified plugins/contrib/source_exporter/Exporter_wx32_64.cbp plugins/contrib/source_exporter/Exporter_wxMSW32-msys2.cbp > Exporter.diff
diff --ignore-space-change --unified plugins/contrib/SpellChecker/SpellChecker_wx32_64.cbp plugins/contrib/SpellChecker/SpellChecker_wxMSW32-msys2.cbp > SpellChecker.diff
diff --ignore-space-change --unified plugins/contrib/symtab/symtab_wx32_64.cbp plugins/contrib/symtab/symtab_wxMSW32-msys2.cbp > symtab.diff
diff --ignore-space-change --unified plugins/contrib/ThreadSearch/ThreadSearch_wx32_64.cbp plugins/contrib/ThreadSearch/ThreadSearch_wxMSW32-msys2.cbp > ThreadSearch.diff
diff --ignore-space-change --unified plugins/contrib/ToolsPlus/ToolsPlus_wx32_64.cbp plugins/contrib/ToolsPlus/ToolsPlus_wxMSW32-msys2.cbp > ToolsPlus.diff
diff --ignore-space-change --unified plugins/contrib/wxContribItems/wxContribItems_wx32_64.cbp plugins/contrib/wxContribItems/wxContribItems_wxMSW32-msys2.cbp > wxContribItems.diff
diff --ignore-space-change --unified plugins/contrib/wxSmith/wxSmith_wx32_64.cbp plugins/contrib/wxSmith/wxSmith_wxMSW32-msys2.cbp > wxSmith.diff
diff --ignore-space-change --unified plugins/contrib/wxSmithAui/wxSmithAui_wx32_64.cbp plugins/contrib/wxSmithAui/wxSmithAui_wxMSW32-msys2.cbp > wxSmithAui.diff
diff --ignore-space-change --unified plugins/contrib/wxSmithContribItems/wxSmithContribItems_wx32_64.cbp plugins/contrib/wxSmithContribItems/wxSmithContribItems_wxMSW32-msys2.cbp > wxSmithContribItems.diff
